// SPDX-License-Identifier: AGPL-3.0-or-later

package accept

import (
	"errors"
	"net"
	"testing"
	"time"
)

// Same errDispatcher from zz_jsonfallback_err_test.go but exercised
// through handleJSONConn rather than handleBinaryConn.
func runJSONConnTest(t *testing.T, d Dispatcher, body []byte) {
	t.Helper()
	a := NewAcceptor(100, d)
	srv, cli := net.Pipe()
	defer srv.Close()
	defer cli.Close()
	go func() {
		buf := make([]byte, 4096)
		for {
			if _, err := cli.Read(buf); err != nil {
				return
			}
		}
	}()
	done := make(chan struct{})
	go func() {
		a.handleConn(srv)
		close(done)
	}()
	writeJSONFrame(t, cli, body)
	time.Sleep(50 * time.Millisecond)
	cli.Close()
	select {
	case <-done:
	case <-time.After(2 * time.Second):
		t.Fatal("handleConn blocked")
	}
}

func TestJSONConn_KnownErrorMessagesPropagate(t *testing.T) {
	t.Parallel()
	cases := []string{
		"rate limited",
		"enterprise feature: required",
		"key expired at 2026-01-01",
		"already a member",
		"node 1 is not a member",
		"cannot demote owner",
		"too many tags",
		"hostname too long",
		"node 9999: not found",
		"invalid foo",
		"requires admin",
		"signature verification failed",
	}
	for _, msg := range cases {
		t.Run(msg, func(t *testing.T) {
			d := &errDispatcher{errToReturn: errors.New(msg)}
			runJSONConnTest(t, d, []byte(`{"type":"x"}`))
		})
	}
}

func TestJSONConn_GenericErrorBecomesRequestFailed(t *testing.T) {
	t.Parallel()
	d := &errDispatcher{errToReturn: errors.New("an unrelated error")}
	runJSONConnTest(t, d, []byte(`{"type":"x"}`))
}

func TestJSONConn_RawResponseSentinel(t *testing.T) {
	t.Parallel()
	d := &errDispatcher{rawResp: []byte(`{"pre":"baked"}`)}
	runJSONConnTest(t, d, []byte(`{"type":"x"}`))
}

// TestSetTLS_ConfigureBranches covers the TLS configuration paths.
func TestSetTLS_AutoGenerated(t *testing.T) {
	t.Parallel()
	d := &fakeDispatcher{}
	a := NewAcceptor(10, d)
	if err := a.SetTLS("", ""); err != nil {
		t.Errorf("SetTLS auto: %v", err)
	}
	if a.tlsConfig == nil {
		t.Error("tlsConfig not set")
	}
}
